import { config } from 'dotenv';

config();

const { PORT, NODE_ENV, DB_URL, BASE_URL, SWAGGER_TITLE, SWAGGER_DESCRIPTION, SWAGGER_SERVER_DESCRIPTION, JWT_SECRET_KEY, JWT_EXPIRES_IN, JWT_COOKIE_EXPIRES_IN } = process.env;

export const Config = { PORT, NODE_ENV, DB_URL, BASE_URL, SWAGGER_TITLE, SWAGGER_DESCRIPTION, SWAGGER_SERVER_DESCRIPTION, JWT_SECRET_KEY, JWT_EXPIRES_IN, JWT_COOKIE_EXPIRES_IN };
