import { config } from 'dotenv';

config();

const { PORT, NODE_ENV, DB_URL, BASE_URL, SWAGGER_TITLE, SWAGGER_DESCRIPTION, SWAGGER_SERVER_DESCRIPTION } = process.env;

export const Config = { PORT, NODE_ENV, DB_URL, BASE_URL, SWAGGER_TITLE, SWAGGER_DESCRIPTION, SWAGGER_SERVER_DESCRIPTION };
